# Generated by Django 4.2.16 on 2024-11-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_enquiry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Product',
            new_name='product',
        ),
    ]
